name: Automate PR merge

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  automate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Execute script
        run: |
          node -e "require('./merge_prs').mergePullRequests(github, context)"
